name: Build and Deploy App and Infrastructure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Setup Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Specify your Node.js version

    # Install dependencies
    - name: Install dependencies
      run: |
        cd test-app
        npm install

    # Generate Prisma client
    - name: Generate Prisma Client
      run: |
        cd test-app
        npx prisma db seed
        npx prisma generate

    # Build, tag, and push the Docker image to Amazon ECR
    - name: Build the project
      run: npm run build

    - name: Start the application
      run: npm run dev &
    - name: Wait for the server to be ready
      run: |
        until $(curl --output /dev/null --silent --head --fail http://localhost:3000); do
          printf '.'
          sleep 1
        done
    - name: Run Cypress E2E Tests
      run: npm run test:e2e
