name: Build and Deploy App and Infrastructure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to AWS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Setup Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Specify your Node.js version

    # Install dependencies
    - name: Install dependencies
      run: |
        cd test-app
        npm install

    # Generate Prisma client
    - name: Generate Prisma Client
      run: |
        cd test-app
        npx prisma generate

    # Build, tag, and push the Docker image to Amazon ECR

    # Deploy CDK Stack
