name: Build, Test and Deploy App

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Setup Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Specify your Node.js version

    # Install dependencies
    - name: Install dependencies
      run: |
        cd test-app
        npm install

    # Security Audit
    - name: Run npm audit
      run: |
        cd test-app
        npm audit --production --audit-level=moderate
      continue-on-error: false

    # Generate Prisma client
    - name: Generate Prisma Client
      run: |
        cd test-app
        npx prisma db seed
        npx prisma generate

    # Build the project
    - name: Build the project
      run: |
        cd test-app
        npm run build
        
    # Run unit tests
    - name: Run Unit Tests
      run: |
        cd test-app
        npm test

    # Run E2E tests
    - name: Start the application
      run: |
        cd test-app
        npm run dev &
    - name: Wait for the server to be ready
      run: |
        cd test-app
        until $(curl --output /dev/null --silent --head --fail http://localhost:3000); do
          printf '.'
          sleep 1
        done
    - name: Run Cypress E2E Tests
      run: |
        cd test-app
        npm run test:e2e
      env:
        POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
        KV_REST_API_URL: ${{ secrets.KV_REST_API_URL }}
        KV_REST_API_TOKEN: ${{ secrets.KV_REST_API_TOKEN }}
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

  # Deploy the stack to Vercel
  deploy:
    name: Deploy
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Vercel
        run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}
